### ISSUE TITLE
Template language file?

### ISSUE THREAD

**Issue by rasmusolle** [WohlSoft/PGE-Project#131]
Is there some template language file for PGE editor?

**Comment by Wohlstand** [comment]
There are TS-files in the Editor/languages/, and I pre-generated some blank translations for languages: Bulgarian, French, Indonesian, Japanese, Chinese, Netherlander, Ukrainian. If you want make a new language file:
* you need to have full Qt (take here http://qt.io/download-open-source/)
* clone entire repo of PGE via any git client
* Then open pge.pro in the Qt Creator (confirm suggested project preferences and continue)
* Edit the [Editor/languages.pri](https://github.com/Wohlhabend-Networks/PGE-Project/blob/master/Editor/languages.pri) file and:
```QMake
TRANSLATIONS += \
    $$PWD/languages/editor_en.ts \
    $$PWD/languages/editor_ru.ts \
    .... \
    $$PWD/languages/editor_id.ts
```
Append new line:
```QMake
TRANSLATIONS += \
    $$PWD/languages/editor_en.ts \
    $$PWD/languages/editor_ru.ts \
    .... \
    $$PWD/languages/editor_id.ts \
    $$PWD/languages/editor_se.ts
```
(but, all previous lines must end with "\", so, don't break QMake syntax)
* In the menu "Tools -> External -> Linguist -> Refresh translations (lupdate)" and wait few seconds. You must find in the Editor/languages/ folder your just generated translation file.

Same way to take a blank translation of unlisted language on the PGE Engine, but stuff you needed in the Engine folder

Anyway, here I also wrote how to make language template:
http://wohlsoft.ru/forum/viewtopic.php?f=5&t=117

**Comment by Wohlstand** [comment]
Closing because of a long time no reply. Also, since moving on CMake, there are different files that are specifying languages.

**Comment by Wohlstand** [comment]
@rasmusolle, ping!
If you want to work on translation, since a week ago here is WebLate now using by PGE:
https://hosted.weblate.org/projects/pge-project/
Feel free to register and work on translation :fox_face: :wink:
