### ISSUE TITLE
[Editor, LunaLua frontnend] Music does not auto-resume in editor after terminating Luna-Tester.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#142]
Title says all.

**Comment by Wohlstand** [comment]
That a LunaLUA side task which must send IPC message to PGE Editor to tell it resume music. By default I don't locking music player while doing tests with LunaLUA, but locking while using PGE Engine.

**Comment by Wohlstand** [comment]
This is LunaLua side imperfection was been fixed since SMBX2b4p1 (probably). The latest state resolves this problem.
