### ISSUE TITLE
[Editor] Uncontrollable block placement after placing while scrolling

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#150]
Finally managed to hunt down that bug that was existing in earliest alphas of PGE editor.
1. Pick a block from tileset. 
2. Hold arrow key on keyboard to scroll section view in one direction.
3. Press and release mouse button in the scene while still holding arrow key to place some blocks. Don`t release arrow key yet.
4. Press and release mouse button again while still holding arrow key on keyboard.

After second mouse button release blocks don`t stop placing and continue to place uncontrollably, if you use arrows to scoll around section. Furthermore, blocks placed by bug are not recorded in history so bug effect requires manual erasing of placed blocks (and restoring what was overwritten).

Video: https://yadi.sk/i/2wM0r_PxvJrwf

**Comment by Wohlstand** [comment]
Known and old bug...
However now I in process to implementing a new item scene implementation to replace huge QGraphicsScene which forced me to have a tonn of workarounds to deal with it. QGraphicsScene and workarounds over it an answer of wired bugs against context menu tricks (which are was in early builds), etc.

**Comment by Wohlstand** [comment]
I have fixed this some weeks/months ago: reason of this silly bug was a rejecting of mouse release event in some condition that makes this dumb thing appear.
