### ISSUE TITLE
Flood fill fails to fill top row of blocks in section

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#151]
Video says all: https://yadi.sk/i/pblBrMTQvJsph

**Comment by Wohlstand** [comment]
That easy to fix with grid aligning of section box sides to let blocks be placed right

**Comment by Wohlstand** [comment]
That has been fixed
![1_section_1_936145377](https://cloud.githubusercontent.com/assets/6751442/18611196/41ed7a44-7d43-11e6-8ad2-7b532d0e0422.png)
