### ISSUE TITLE
Character don`t get crushed if pinched to floor by downwards autoscroll.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#152]
Title says all.

Test level: https://yadi.sk/d/ZMqCSufgvQNy4

**Comment by Wohlstand** [comment]
I even wasn't added limiting player's highest Y position after section's top, but I think, it's time to implement that now

**Comment by Alucard648** [comment]
So you mean like this:
![autoscroll_down_dead](https://cloud.githubusercontent.com/assets/7596025/18691753/368b354e-7f9e-11e6-8b9e-3bd22fc152ab.png)
Character was killed by autoscroll if was scrolled off top of the camera/section by 32 pixels while standing/walking on ground.

**Comment by Wohlstand** [comment]
yea, that

**Comment by Wohlstand** [comment]
Just implemented stuff

**Comment by Alucard648** [comment]
It Works!
