### ISSUE TITLE
Online downloader crashes when Avast blocks download. 

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#155]
I hate that thing...
![avast1](https://cloud.githubusercontent.com/assets/7596025/19231007/4b1cc076-8ee0-11e6-8d79-c2730a371e12.png)

**Comment by Wohlstand** [comment]
Just sent report to Avast's support (Heruistic analysis is totally sucks, but HIPS-based scanning must be more accurate than heruistic scaner which always produces false positives to everything. Fun fact: McAfee antivirus broke true Windows XP's svrchost.exe and caused boot-loop)

**Comment by Alucard648** [comment]
Avast still blocks online installation.

**Comment by Wohlstand** [comment]
Does it attacks now or not?

**Comment by Alucard648** [comment]
Still blocks install.

**Comment by Alucard648** [comment]
Antivirus issue has been resolved.
