### ISSUE TITLE
Tips of the Day proofread report

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#159]
- [x] 1.
![t1](https://cloud.githubusercontent.com/assets/7596025/19513304/251a806a-95f8-11e6-8a75-88c09a7ba9d6.png)
complete list

- [x] 2.
![t4](https://cloud.githubusercontent.com/assets/7596025/19513331/3bbdd394-95f8-11e6-8263-bb5c1430424e.png)
there->they

- [x] 3.
![t6](https://cloud.githubusercontent.com/assets/7596025/19513375/5ce12882-95f8-11e6-91ac-a296279a076a.png)
placement ("a" is not needed)
rectangle
Also circle fill tool note is missing here.

- [x] 4.
![t7](https://cloud.githubusercontent.com/assets/7596025/19513462/9f90e03c-95f8-11e6-81ca-92b8c761cea9.png)
music
music files

- [x] 5.
![t8](https://cloud.githubusercontent.com/assets/7596025/19513484/bca7a200-95f8-11e6-8cf5-6e829cd29c82.png)
Didn`t you know
"a" is excessive

- [x] 6.
![t10](https://cloud.githubusercontent.com/assets/7596025/19513526/de051ab8-95f8-11e6-9f24-6f613f95788f.png)
held

- [x] 7.
![t8](https://cloud.githubusercontent.com/assets/7596025/19513546/f04ddc6e-95f8-11e6-8e6c-b77df4848f86.png)
F8 reloads the level, not F5

**Comment by Wohlstand** [comment]
Everything here has been fixed
