### ISSUE TITLE
Warps and Doors properties widget is not dockable.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#161]
![warp_dock](https://cloud.githubusercontent.com/assets/7596025/19515917/303a7108-9602-11e6-9ee7-2b90ffee5ec2.png)
Sreenshot says all.

**Comment by Wohlstand** [comment]
It's dockable, you must move mouse cursor with grabbed toolbox to main window's side until you will see expanded area to dock it

**Comment by Alucard648** [comment]
This works with all other widgets (layers, tileset item box, section settings et.) but not with Warps&Doors one.

**Comment by Wohlstand** [comment]
for me works for both left and right sides (latest build):
![2016-10-19 13-52-02](https://cloud.githubusercontent.com/assets/6751442/19516135/a421d29c-960b-11e6-9546-8d3ad408ad55.png)
I checked code and it's no any

**Comment by Alucard648** [comment]
I am guessing, it`s a Linux build, check the Windows one.
Video of bug in action: https://yadi.sk/i/9KAbV1LVx8yJf

**Comment by Wohlstand** [comment]
![2016-10-19 15-39-40](https://cloud.githubusercontent.com/assets/6751442/19518931/adc27d2e-961a-11e6-8f02-8a114ded94ef.png)
Just built latest code on Windows and tested - everything is fine. Try take latest laboratory build and retry

**Comment by Alucard648** [comment]
Just installed today`s laboratory build. Bug still persists.

**Comment by Wohlstand** [comment]
Then try to clean up in the pge_editor.ini (while editor is off) all geometry and state parameters, then  try again

**Comment by Alucard648** [comment]
That INI file has nothing but "force-portable" setting.

**Comment by Wohlstand** [comment]
TRUE settings ini now in "settings" subfolder. I moved it to don't cause troubles while updating from zip by file replacing

**Comment by Alucard648** [comment]
Found and tried to do so. Bug still persists.

**Comment by Wohlstand** [comment]
Try to undock all widgets and then try to dock them

**Comment by Alucard648** [comment]
It works... But only in full-screen mode, not widowed mode. I usually just maximizing window, instead of turning on full-screen.

**Comment by Wohlstand** [comment]
So, it's another reason to add a scroll area into this toolbox

**Comment by Alucard648** [comment]
Warps/doors now docks as intended.

**Comment by Wohlstand** [comment]
Oh, maybe it won't be docked because area was smaller than widget itself? (I have 1280x1024 at home and HD at job, and in both cases I have window bigger)
