### ISSUE TITLE
Editor tries to switch focus to non-existent Item Properties widget.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#162]
1. Turn on "Don`t show Item Properties on placing" in Editor Settings.
2. Dock item palette widget (either Level Item Box or Tileset item Box) and Item Properties to the same side.
3. Select an item from palette.

Result: https://yadi.sk/i/CDE7aPxIxWoQm

**Comment by Wohlstand** [comment]
Please check out thins. I has been fixed this.

**Comment by Alucard648** [comment]
Thanks for fixing this rather old bug.
