### ISSUE TITLE
Editor fails to detect engine termination.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#164]
1. Open level in editor.
2. Hit F5 to test level in PGE engine.
3. Terminate engine in any way.
4. F5 again.

Editor fails to recognize that that engine is already terminated and prompts to abort testing.

**Comment by Wohlstand** [comment]
Seems engine's process turned into zombie after closing. It's engine-side bug on Windows

**Comment by Alucard648** [comment]
Checked task manager. Zombie confirmed.

**Comment by Wohlstand** [comment]
Try now: https://github.com/WohlSoft/PGE-Project/commit/38c4a6e9a30e0cde2bf619bedd3bb24a66b7aba8
Must be fixed

**Comment by Alucard648** [comment]
Zombie defeated.

**Comment by Wohlstand** [comment]
![zombie](http://www.486games.net/old/138_4.gif)
