### ISSUE TITLE
[Editor] F5 key does not work with testing world maps.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#167]
Title says all.
![world_editor](https://cloud.githubusercontent.com/assets/7596025/20067860/c99d2014-a527-11e6-9f9e-e017eca3aecf.png)

**Comment by Wohlstand** [comment]
I think, I'll allow that menu item to don't swap hot keys every window switch

**Comment by Wohlstand** [comment]
Has been implemented! https://github.com/WohlSoft/PGE-Project/commit/b8e907add7cce32b36dcac9b02c82edd93a10b91

**BUT:** 

> Was not tested on LunaTester yet (LunaTester does test menu modification with dynamical adding of two sub-menus and moving PGE's test actions into one of them. Newly-added world map testing menu item would be show incorrectly, tomorrow will check out for this thing and will fix it)
