### ISSUE TITLE
Position bookmarks can corrupt world map files.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#169]
1. Zoom out to 57%-87% rate.
2. Add position bookmark.
3. Save the file.

Upon reopening, I got this:
![corrupted1](https://cloud.githubusercontent.com/assets/7596025/20068085/85639fee-a528-11e6-9c1c-50bf4f38c6f4.png)
Had to use text editor to fix corrupted world map file.

**Comment by Wohlstand** [comment]
That value must be stored as integer,  So, it's small issue, will fix when I'll come to home

**Comment by Wohlstand** [comment]
P.S. Same crap can happen also with level and meta-file for SMBX64 files (a file which saves the impossible in the old format data). However I have being fixed that

**Comment by Alucard648** [comment]
Bugfix confirmed.
