### ISSUE TITLE
Engine segfaults on startup

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#173]
![engine_segfault](https://cloud.githubusercontent.com/assets/7596025/20241388/0e02eb98-a939-11e6-9033-8d1841aee01c.png)
Yep.

**Comment by Wohlstand** [comment]
That an SDL-side (SDL.dll) bug which I have been fixed myself
https://bugzilla.libsdl.org/show_bug.cgi?id=3488#c7
Wait until I will rebuild fixed SDL.dll. Crash also may happen in the editor when you will try to test various sounds.

**Comment by Wohlstand** [comment]
Rebuilt!
So, you can try now (must not crash)

**Comment by Alucard648** [comment]
No crashing.
