### ISSUE TITLE
Issues with flagging level as modified.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#174]
Related to #160.
The following in-editor actions don`t flag level as modified:

1. Editing item properties without moving them.

2. Editing warps and doors.

3. Editing position bookmarks.

4. Deleting events.

5. Flipping and rotating a section.

Issues 1 & 3 is also applicable to world map editing.

**Comment by Wohlstand** [comment]
Please check

**Comment by Alucard648** [comment]
Everything is fine.
