### ISSUE TITLE
Event editing fails to be undone properly

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#175]
1. Open a level that has events.
2. Edit an event, like change sound to play.
3. Hit "undo".
4. Run testing.

Event edit still in place, even if it counted as undone in history.

**Comment by Wohlstand** [comment]
This toolbox still lack property history manager action tracking, therefore some actions aren't tracked. New history manager I designed together with Kevsoft I'll apply after reorganizing. It allows much easier add tracking of new edit actions which I needed myself to speed-up implementation of new UI controlls (especially lot of extra controls provided by 38A standard and to have an ability to quickly add own features). I can implement some actions quickly, but there are will not be tracked in the history manager which will make some confusion when you trying to jump between history states

**Comment by Wohlstand** [comment]
This I will try to fix tomorrow. But after next release, I though, and I will rebuild base completely in separated folder

**Comment by Wohlstand** [comment]
Must be fixed now. Bug is really dumb, because history events are stored by incorrect function call

**Comment by Alucard648** [comment]
Bugfix works fine.

**Comment by Wohlstand** [comment]
Great!
So, at now I will make tiny cosmetic change (add scroll area into warps dialog) and will publish release

**Comment by Alucard648** [comment]
And fix warps dialog not docking to sides via dragging in windowed mode.

**Comment by Wohlstand** [comment]
> And fix warps dialog not docking to sides via dragging in windowed mode.

That seems is Qt-side bug which rarely appears only on Windows OS. Anyway, try that now, because possibly that was caused by wrong event processing in properties dialog which I was been destroyed to avoid any possible crap caused by it.

**Comment by Alucard648** [comment]
> Anyway, try that now, because possibly that was caused by wrong event processing in properties dialog which I was been destroyed to avoid any possible crap caused by it.

Still fails to dock as mentioned above.

**Comment by Wohlstand** [comment]
> Still fails to dock as mentioned above.

Anyway, since base for next version will be completely rebuilt, this bug must go away
