### ISSUE TITLE
More typoes found in engine translation texts

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#176]
Just finished proofreading engine translation files. Here is what I found:
"abourted" -> aborted
"процессра" -> процессора
"Показ. отдад. инфо" -> Показ. отлад. инфо
"Вкл. вертик. синхр" -> Bкл. вертик. синхр.
The last typo is just missing point at the end.

**Comment by Wohlstand** [comment]
* "abourted" is right form for British English (opposite to American form "aborted")

**Comment by KevinW1998** [comment]
Ehm.... since when?

**Comment by Wohlstand** [comment]
Everything has been fixed!
