### ISSUE TITLE
Custom data folder support for world map/s

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#177]
Title says all. As for now, world map custom stuff clogs game`s root directory very heavy.

**Comment by Wohlstand** [comment]
Already supported by both editor and engine since foundation. Custom folder name is equal to world map's file name. (or it can be quickly created on "save as" where you checked "create custom folder").
Doesn't supported by SMBX Engine.

**Comment by Alucard648** [comment]
Thanks for quick response. At first, I thought there is no such thing done, right after hitting Save As on world map editor...

**Comment by Wohlstand** [comment]
Also that needed for a future ability to have multiple world maps per episode and own settings file for episode which will list all world map files. (I think, this I will do when I will completely implement SMBX64 Standard base for PGE Engine to let it be ready-to-play thing)

**Comment by Wohlstand** [comment]
Closed since custom folder for world maps already implemented.

**Comment by Alucard648** [comment]
Yet it`s still needed to add "Make custom data folder" checkbox on Save As command
![make_custom_folder](https://cloud.githubusercontent.com/assets/7596025/20671982/ae30e33c-b590-11e6-8f30-eeff43bd298b.png)

**Comment by Wohlstand** [comment]
Seems Kevin was disabled it for world map long time ago to don't confuse people who making episodes for legacy SMBX Engine. I think, I'll add notice "Not supported for SMBX Engine!" to avoid confusions
