### ISSUE TITLE
SDL2 Music player crashes on attempt to play uncompressed WAV file

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#181]
Title says all.
Tested on this sound archive: https://yadi.sk/d/Wa7j4xPT32AuHw
Archive came from Sounds Resource: https://www.sounds-resource.com

**Comment by Wohlstand** [comment]
This is a trouble of resampling (upsampling) implementation. I tried to implement the own resampling code which improves quality of resulted sound. Original implementation was more stable (wasn't resulted crashes), but upsampling of WAV playing always resulted creepy and choppy sound. My implementation is completely avoids this and results stable sound (no chops and less junk noise). However, this part still require some improvements of memory management to avoid any crashes while doing this. You can escape this crash by manual upsamling of all WAVs into 44100 via SoX or via Audacity.

**Comment by Wohlstand** [comment]
Please try now (after it will be uploaded)

**Comment by Alucard648** [comment]
Mine also works. But WAV playback is still far from optimal.

**Comment by Wohlstand** [comment]
That because resampler without interpolation which results extra artifacts on it. That another issue. Main question of crashes has been fixed.
Try for experimental example any mp3/ogg/flac into 11050 or into 8000 and try to play

**Comment by Wohlstand** [comment]
Resolving of quality of resampling is another issue
