### ISSUE TITLE
SoX audio converter - Coversion results message window is too tall.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#184]
Resampled sound pack from #181 to 44100Hz and got this:
![sox_audio](https://cloud.githubusercontent.com/assets/7596025/21156244/31ef1864-c186-11e6-815f-cf591abe3a7d.png)
This window can only be closed with Enter key. After conversion sounds play fine in PGEMusPlay.

**Comment by Wohlstand** [comment]
Those warnings spawned by SoX utility yea, my mistake....
I think, I will just have dialog with a scrollable text-box inside instead this.
SoX converted all sounds right, but it found something "non-usual" and printed as warning

**Comment by Wohlstand** [comment]
Fixed!
![2016-12-14 00-46-34](https://cloud.githubusercontent.com/assets/6751442/21160848/cf00bf90-c19f-11e6-89b5-8240e7602860.png)

**Comment by Alucard648** [comment]
Thanks for mentioning about log file, as well, as fixing enormous window generation.
