### ISSUE TITLE
Search engine does not cycle through found items in wrap-around.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#187]
1. Input a search query so only a few items fit to it For SMBX instance, NPC ID #274 (Ace Coin).
2. Keep hitting "Next NPC/Block/BGO" button.

Instead of cycling trough search results, the search will get stuck on a certain item, apparently latest placed in the level.

**Comment by Wohlstand** [comment]
Ouch, seems something accidentally broken, will fix that

**Comment by Wohlstand** [comment]
Just now I have been fixed it!
You can try this!

**Comment by Alucard648** [comment]
Thanks for fixing. Keep going!
