### ISSUE TITLE
SNES-like sound bank for Timidity

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#198]
I have seen mentioning about this side project during earlier stages of PGE development, but now it went all quiet. Any thoughts?

**Comment by Wohlstand** [comment]
That bank is still be available, and newer version you can find here: https://yadi.sk/d/bky-syShwpTRH
Sometimes I testing it and updating any instruments in it, but rare

**Comment by Alucard648** [comment]
Any instructions on how to set it up to work with SDL Mixer and PGE Musplay?
