### ISSUE TITLE
[Engine] Engine Fails to Render Correctly on high-dpi Resolutions

### ISSUE THREAD

**Issue by suicvne** [WohlSoft/PGE-Project#199]
(I've only tested this on macOS)

When running the PGE Engine on a high-DPI display, the engine will only render in the lower left corner of the window. 

<img width="912" alt="screen shot 2017-03-17 at 8 21 55 am" src="https://cloud.githubusercontent.com/assets/861492/24043474/29b55702-0aed-11e7-8576-fef7d1b24d93.png">

A temporary fix for this on macOS is to right click on the PGE Engine.app->Get Info->and check off "Open in Low Resolution Mode"

![screen shot 2017-03-17 at 8 21 01 am](https://cloud.githubusercontent.com/assets/861492/24043495/419e53d2-0aed-11e7-8c0d-fc919e7edeb7.png)

**Comment by Wohlstand** [comment]
Also that bug disappears when you will try to move window

**Comment by Wohlstand** [comment]
Okay, I found another tip:

> On Apple's OS X you must set the NSHighResolutionCapable Info.plist property to YES, otherwise you will not receive a High DPI OpenGL canvas. 

So, my experiment is: https://github.com/WohlSoft/PGE-Project/commit/c85d0209abb079c2ebb0a6d95834d5024e9f2a55
Waiting when it will be auto-built

**Comment by Wohlstand** [comment]
This change https://github.com/WohlSoft/PGE-Project/commit/a3851a7deede48b4e13192aa694063db2aedbcf8 fixes this bug. I'll close this afrer I'll test same on iMac of my colleague at evening

**Comment by Wohlstand** [comment]
Okay, I have tested engine on my colleague's iMac and it works perfectly!
