### ISSUE TITLE
[Engine] Savestate save/load cheat/function.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#201]
Suggestion was inspired by emulator savestate function. Can be accessed by cheat or via script function.

**Comment by Wohlstand** [comment]
In a case of here, it would be a dump of all level in-memory objects:
* All existing objects with their coordinates, preferences, momentum values
* States of all layers
* Contents of any event queues (there are usually containing lamda-functions with captured values that I don't think is easy to save into the file)
* All states of the script engine which I also don't think easy to dump and then restore. (Anyway, dumping of script engine states is possible for the debug purposes to allow programmers to analyze them)
I think that can be discussed for any possibilities

**Comment by Bluenaxela** [comment]
Saving the state of the LuaJIT engine is not very feasible, particularly if any scripts use coroutines (which are very very useful).

If one was using Lua 5.2, there would be https://github.com/fnuecke/eris which would allow fully saving the engine's state (though you'd still have some challenges related to C++ objects Lua code holds references to).... but this does not work for LuaJIT. Biggest difficulty in why it doesn't work for LuaJIT sounds to be related to coroutines.
See issue 4 is eris
also http://lua-users.org/lists/lua-l/2008-09/msg00000.html

All in all, this is why I say saving the state of a LuaJIT scripting engine, is not very feasible at all.

**Comment by Wohlstand** [comment]
Closed because of explained reason of impossibility of this thing
