### ISSUE TITLE
[Overworld testing] Dummy level entrance message has missing file path string.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#202]
![dummy_level_bug](https://cloud.githubusercontent.com/assets/7596025/24324535/4b2ca108-1199-11e7-931e-55bd2001e070.png)
Screenshot says all.

**Comment by Wohlstand** [comment]
For that I need to implement the conversion of QString's arguments into fmt:: , even because of compatibility of translations are still use %* way for arguments

**Comment by Wohlstand** [comment]
Fixed!
![2017-03-26 05-51-32](https://cloud.githubusercontent.com/assets/6751442/24328063/758cf250-11e8-11e7-91db-0d11c71c2f81.png)

**Comment by Alucard648** [comment]
Another message has missing strings: level warp during testing dummy message:
![string_bug_2](https://cloud.githubusercontent.com/assets/7596025/24329038/244fe224-1203-11e7-8eb0-b0c1d1d8fa51.png)

**Comment by Wohlstand** [comment]
Fixed too!
![2017-03-26 14-06-06](https://cloud.githubusercontent.com/assets/6751442/24330719/70a498ca-122d-11e7-8e6e-ebb8c5c75beb.png)
