### ISSUE TITLE
[Engine] Crash on level startup if there are NPC`s in level.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#203]
![engine_crash](https://cloud.githubusercontent.com/assets/7596025/24329049/873614d0-1203-11e7-8bb1-44899dc3db47.png)
Also the same crash happens on attempt to spawn NPC.
Also: where is that poor "beaten cat" image from crash handler?

**Comment by Wohlstand** [comment]
1) Will check
2) PGE Engine is not using same dialog, instead you can look for crash specs in the log (for now I have to spawn many information into log file include detailed information about happened crash)

**Comment by Wohlstand** [comment]
I have been fixed a random generator and now you can to try the result.

**Comment by Alucard648** [comment]
It works.
