### ISSUE TITLE
Blocks per second calculator does not allow to input negative values into left field.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#207]
Title says all. Just a minor inconvenience.
![default](https://cloud.githubusercontent.com/assets/7596025/25139035/c8216dfa-2464-11e7-8776-1cf64fe9e325.png)

**Comment by Wohlstand** [comment]
Easy to fix, wait a sec

**Comment by Wohlstand** [comment]
Done! Try after ~20 minutes when laboratory build will be assembled

**Comment by Alucard648** [comment]
Thanks.
