### ISSUE TITLE
[Engine] Frame rate proggressively drops with each call of event that moves the layer.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#208]
Test level: https://yadi.sk/d/5L50KLQI3H7AgC
As the player progresses trough vertical autoscroll section, the frame rate drops considerably.

**Comment by Wohlstand** [comment]
This is an old issue that now in-works in the "experimental-subtrees" branch which includes lots of other things are related to layer motion and NPC sticking in common

**Comment by Wohlstand** [comment]
I have merged the "experimental-subtrees" branch into master, so, any new changes are will be available now in laboratory builds, so, you can test out this

**Comment by Alucard648** [comment]
So far, so good. The test tree level works fine.
