### ISSUE TITLE
[PGE Wiki] Split Game Configuration Pack References page into separate pages.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#218]
As PGE engine feature list expands, the documentation page can eventually bloat beyond readability. Splitting it into separate pages per table might solve this potential issue.

**Comment by Wohlstand** [comment]
I also have this idea and I think to nearest time to split that page, even now it's already huge

**Comment by Wohlstand** [comment]
Just now I have splitted down the whole config pack reference into per-page reference:
https://wohlsoft.ru/pgewiki/Game_Configuration_Pack_References
