### ISSUE TITLE
[Editor] Replace combo-box with tab panel in the tileset item boxes

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/PGE-Project#222]
Requested by @Hoeloe
> would it be possible
to change this
![unknown1](https://user-images.githubusercontent.com/6751442/28566477-f283b1d2-7137-11e7-93d2-21c05303e405.png)
to this
![unknown2](https://user-images.githubusercontent.com/6751442/28566507-097c173a-7138-11e7-8a26-112e1b0edcd7.png)
the dropdown selection is very... 2004

**Comment by Alucard648** [comment]
Indeed. Having to regularily open this drop-down list is quite annoying. Especially with the absense of "Favorites"/"Recently used" item lists.

**Comment by Shadowblitz16** [comment]
I agree tabs should be used instead of a combobox

**Comment by Wohlstand** [comment]
Implemented! https://github.com/WohlSoft/PGE-Project/commit/7e696b759e2634335c27d05d30ecd1cf3e59c7f9
