### ISSUE TITLE
Avast treats latest online installer as virus.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#230]
Damned antivirus.
![avast_fail2](https://user-images.githubusercontent.com/7596025/29878061-2e1c1444-8daa-11e7-898a-93f5e68adc66.png)

**Comment by Wohlstand** [comment]
Just download it ten times on different devices to stop this crap (suggestion I have got from official long times ago to stop DRep alert).
DRep is paranoia for any "unknown files"

**Comment by Alucard648** [comment]
Where can I get 10 different devices to download into? Or just it goes away after 10 download fails?

**Comment by Wohlstand** [comment]
I think, we can just ask at least ten of community people who has Avast to download those files

**Comment by Wohlstand** [comment]
Okay, I made experimental InnoSetup-based installer http://wohlsoft.ru/docs/_laboratory/installers/pge-online-installer-innosetup.exe which you can try out. Now it has self-update checking. So, if I need to update installer itself, I will only change a version number on the server side

**Comment by Alucard648** [comment]
Avast blocks InnoSetup-based installer. DRep

**Comment by Alucard648** [comment]
As for now, old NSIS installer no longer treatead as virus...
