### ISSUE TITLE
Editor Settings - Radio button collides with frame.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#232]
![radio](https://user-images.githubusercontent.com/7596025/29971737-0a5424c8-8f32-11e7-8352-201ea6967a81.png)
Minor, but still...

**Comment by Wohlstand** [comment]
Those groups are was a pain on different platforms where UI elements are having different sizes (biggest are on macOS) and worse glitches are was. I'll apply this fix into new base of editor

**Comment by Wohlstand** [comment]
Fixed! I have added the paddings to left and right sides inside that group box. I hope, this is fixed now! :fox_face:

**Comment by Alucard648** [comment]
Bugfix confirmed, as of latest build.
