### ISSUE TITLE
Issues with MIDI playback

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#233]
- [x] Lags horribly in the editor and engine

- [x] Fails to load at all in PGEMusPlay

**Comment by Wohlstand** [comment]
Can confirm same on Windows on my brother's computer. I think I have posted not good state of libSDL2, I'll try to update it or I will revert back to one of old states before lags began. I will also check code which works with libADLMIDI for possible playback lags.

**Comment by Wohlstand** [comment]
I have made a workaround to disable usage of WASAPI in libSDL2: https://github.com/WohlSoft/PGE-Project/commit/87de63e6ad51ee1a8ebef238e96ada3913279dea
Must help. Wait until 64-bit version will be built, then you can try to update laboratory build again

**Comment by Wohlstand** [comment]
I have tested out builds from AppVeyor, now there are in laboratory, and I also have been updated release packages too. I also updated InnoSetup online installer because of small mistake in one of laboratory component URLs

**Comment by Alucard648** [comment]
As of latest build, everything works fine.
