### ISSUE TITLE
[Editor] Allow reload of config pack without all files closed requirement (automatize it!)

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/PGE-Project#245]
As we have discussed with @Hoeloe , it's can be an improvement: when reloading a config pack, automatically unload all opened files to release usage of global graphics and resources. Then, reload the whole global stuff, and load all files back.

> Hoeloe: also it's still really annoying that reloading the configuration pack doesn't close and reopen levels automatically

**Comment by Wohlstand** [comment]
Some related info that can be used to request the restarting itself:
https://stackoverflow.com/questions/5129788/how-to-restart-my-own-qt-application

**Comment by Wohlstand** [comment]
Complete with this: https://github.com/WohlSoft/PGE-Project/commit/700a20da6a65c5882045dff3f1200057db1dc3b1

**Comment by Wohlstand** [comment]
Only one thing is left: when untitled file created on the fly was open, and where it was saved, will not be re-opened after the reload. If it's fine, I'll close this issue.

**Comment by Hoeloe** [comment]
It's not a disaster but it'd be good if it did open after reload.

**Comment by Wohlstand** [comment]
The only a challenge that untitled files aren't returning any file paths even there are was saved after closing. However, to solve this, it's need to make a bridge to capture file path after saving of untitled file. I'll try to make this in evening...

**Comment by Wohlstand** [comment]
Okay, the case of untitled files now is completely solved!
So, when you'll do config pack reload and having untitled files you'll save in this task, there are will be restored like other regular files!

Please test this case!

**Comment by Wohlstand** [comment]
Just now I have fixed another crap that will cause double save request if you have said "No" on the first request.

Now it's fine now. I think, I'll close this.
