### ISSUE TITLE
[Editor] Add the GUI to make easier editing of music path arguments for SDL Mixer X

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/PGE-Project#247]
For now to have using of extra features of SDL Mixer X is needed to append into end of music filename the set of options after the stick `|` separator. (for example, `meow.mid|s3;c2;r1;`). No one will guess there are exists and can be used for advance of MIDI or GME music! Therefore, for GME and MIDI/RMI/KAR/MUS/XMI add the button to show one another toolbox where are will be properties are will give an ability to setup music playback flexibly and easy.

**Comment by Wohlstand** [comment]
Recent update of PGE MusPlay adds the printing of arguments in dependence from the setup:
![default](https://user-images.githubusercontent.com/6751442/45937766-10269e00-bfcc-11e8-9880-069db4a06d48.png)

The last thing is left - implement the GUI on Editor side to edit that on the fly.

**Comment by Wohlstand** [comment]
The draft for the dialog was started. I desired to make it now. It's a time for it!

![Снимок экрана_2020-10-22_01-26-40](https://user-images.githubusercontent.com/6751442/96793774-a7f25280-1405-11eb-8bda-6cd3d327db81.png)
![Снимок экрана_2020-10-22_01-26-20](https://user-images.githubusercontent.com/6751442/96793776-a9237f80-1405-11eb-8ff1-30d604068355.png)

**Comment by Wohlstand** [comment]
Okay, recently I improved that and committed. So, that should appear at Laboratory soon. It works for me.

**Comment by Wohlstand** [comment]
Closing because of no response for the month.

**Comment by sneakernets** [comment]
I think I was tagged in this; does this need further testing?

**Comment by Wohlstand** [comment]
> I think I was tagged in this; does this need further testing?

I think, if you want, you can test this out, and if you found something not good, you can report that :wink:
