### ISSUE TITLE
[Editor] Add the ability to set the default zoom in/zoom out level

### ISSUE THREAD

**Issue by FireSeraphim** [WohlSoft/PGE-Project#249]
Might I suggest a way to tell PGE to set my default "zoom in" view to 50 rather than having to manually set it every time I open a level? 
I find that having the zoom at fifty is ideal for me and allows a nice balance of letting me see much of the level I'm working on while still allowing me enough precision in block and NPC placement. This is keeping in mind that I have a rather unorthodox 1366 x 768 pixel wide monitor (with a 16:9 ratio).

**Comment by Alucard648** [comment]
I also use 50% zoom a lot when working with editor.

**Comment by Wohlstand** [comment]
Made just now!

**Comment by Alucard648** [comment]
Tested. And it works like magic.
