### ISSUE TITLE
[Editor] Partial plugins system (Extra Settings)

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/PGE-Project#251]
Editor even has the complex and wide functionality, will be more handy with having the plugins system. The current base of the Editor is not so good for implementation of the deep plugins system. Deep plugins system means the giving a complex binding into JavaScript which will allow plugins to manipulate editor's internals. That will be possible after the comming internal architecture restructurization.

The only is possible with current base to implement next things:

# Extra properties of every element
- [x] Implement the access to the custom properties set stored in the special meta field inside of every element that will be saved into LVLX files.
- [x] Inside of every element INI file, provide the ability to give another INI (or JSON) file that will declare the list of extra settings elements are will be shown in item properties toolbox or in the separated toolbox which will be openable from the main properties toolbox or from out of the context menu. Custom properties library taken by Kevsoft for some experiments can be used.
- [x] Create documentation for JSON layout of Extra Settings toolbox.
- [x] Add the "tooltip" support.
- ~~Give some JavaScript events and bindings to allow pre-process data and fields of modifying elements.~~ **Move to a new separated task**.
- [x] Provide extra settings support for level sections
- [x] Add support for "Read Only" fields are will never be written on a change
- [x] Add "Item-ID" type with opening of item selection box to choose an item (for example, block, BGO, NPC, or terrain cell, path cell, level point, scenery element, etc.)

**Comment by Wohlstand** [comment]
Working extra settings has been added!
The documentation for that will be published a bit later...

**Comment by Wohlstand** [comment]
Specification has been created!
https://wohlsoft.ru/pgewiki/Extra_Settings_JSON_Layout

**Comment by Alucard648** [comment]
You also need to include recording custom property edits into history, for undo/redo.

**Comment by Wohlstand** [comment]
History is already tracks them :fox_face: :wink:

**Comment by Wohlstand** [comment]
Tooltips now supported!
* https://wohlsoft.ru/wiki/index.php?title=Extra_Settings_JSON_Layout&type=revision&diff=5505&oldid=5473
* https://wohlsoft.ru/wiki/index.php?title=Extra_Settings_JSON_Layout&type=revision&diff=5505&oldid=5473

**Comment by Wohlstand** [comment]
Because of discussion that was some days ago, it's need to implement support for extra settings for level sections. (As example, allow developers to add custom checkboxes for lua-coded environment features, etc.).

**Comment by Wohlstand** [comment]
* Provide extra settings support for level sections

Support was added in begin of February

* Add support for "Read Only" fields are will never be written on a change

Added a "read-only" flag for lineEdit fields and multiLineEdit, also added the "description" type to show textual labels.

* Add "Item-ID" type with opening of item selection box to choose an item (for example, block, BGO, NPC, or terrain cell, path cell, level point, scenery element, etc.)

Added

**Comment by Wohlstand** [comment]
JavaScript extras going to be a separated task, out of this.
