### ISSUE TITLE
[Editor] World map tileset box - separate music box and remove World Itembox

### ISSUE THREAD

**Issue by Hoeloe** [WohlSoft/PGE-Project#252]
The world itembox features are better handled by the tileset itembox. The only thing that isn't are the music tiles. The music tiles should be separated out, and the world itembox removed from the editor (as it will then be useless).

**Comment by Wohlstand** [comment]
The separate music-boxes set toolbox has been made!
https://github.com/WohlSoft/PGE-Project/commit/33af3a31baa251c77df58955f8e51d2d6a670015
Worldmap items browser will be kept for full access to entire itemset of config pack with no matter what tilesets have bound.
