### ISSUE TITLE
[SDL2 Mixer X] Laggy ADL MIDI playback

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#253]
SDL2 Mixer X + PGE MusPlay
Revision 01f5d5a, built at May 27 2018 22:13:12

ADL Midi playback lags, complete with audio distortions. All other supported devices play Midi fine.
Reproducible on any MIDI file.

1. Open MIDI in PGEMusPlay
2. Set MIDI device as ADL Midi

Windows 7

**Comment by Wohlstand** [comment]
I'll check the SDL2, possibly my WASAPI removing patch was broken...

**Comment by Wohlstand** [comment]
Just now I have checked my stuff, and it's no any lags from any synths, even the case I run Windows on a slower VM rather a real hardware which is much powerful on your end...
Try out the latest build just in a case...
Do you using any audio-related software on a side? Something like "ASIO4All"?

**Comment by Alucard648** [comment]
As of latest build, lags are gone.

**Comment by Alucard648** [comment]
As of latest build ADL MIDI playback is still choppy.

**Comment by Wohlstand** [comment]
The question is still: are you are using extra audio specific software on a side? Do you have same computer specs where the stuff is reproducing?

**Comment by Alucard648** [comment]
![system_specs](https://user-images.githubusercontent.com/7596025/40951907-c06d7ccc-6881-11e8-8c79-c39dd37f566d.png)
No other audio software runs parallel to PGEMusPlay.

**Comment by Wohlstand** [comment]
Just now I have sent update of SDL2 tarball, please check when the result will be built. Or, if the build will still lag, try to copy the SDL2.dll from here: https://ci.appveyor.com/project/Wohlstand/pge-project/build/0.4.0.3.1261
(open 32 or 64-bit build, find the artifacts and PGE MusPlay zip, copy the SDL2.dll only from it into the latest state). If the build will still lag, then, it's not related to SDL2.dll, or possibly it's your local issue. Try PGE MusPlay on any other computer you will have around if possible, just for curious...

**Comment by Alucard648** [comment]
Just a quick update on this ticket. Tested 32-bit and 64-bit versions and lag occurs only on 32-bit version of  ADL midi. 64-bit version plays MIDIs fine. Apparently, online installer fails to auto-detect whether it`s a 32-bit CPU or 64 bit one, but it`s a whole other issue.

**Comment by Wohlstand** [comment]
This is VERY weird... Both 32-bit and 64-bit builds of PGE MusPlay are played MIDI files fine...
Anyway, I'll check the 32-bit build log of SDL2 for just in a case...
Just for a case, I'll try to test the player on my brother's machine...

**Comment by Wohlstand** [comment]
So, the another questions:
- WHICH audio driver you are using?
- Which setup of the audio driver you have against it's latency?

**Comment by Wohlstand** [comment]
Anyway, just for a test, try to type in the "raw MIDI arguments" line next string and restart the song:
```
s0;b72;e2;
```
* s0 - use ADLMIDI synth
* b72 - use 72'th bank (use any another)
* e2 - use DosBox OPL3 (2) emulator instead of Nuked OPL3 (0 - Nuked 1.8, 1 - Nuked 1.7 with @troosh's optimizations). DosBox is much faster but less accurate in comparison to real chip. Nuked is VERY accurate as it's the some sort of simulator of the real chip, however, it eats much more power.

**Comment by Wohlstand** [comment]
Another test case:
* Open command line in the same path where `pge_musplay.exe` is placed
* run `set SDL_AUDIODRIVER=winmm`
* run `pge_musplay` and try to play any musics with default behavior, then close player
* run `set SDL_AUDIODRIVER=directsound`
* run `pge_musplay` again and try out same
* say, which difference between of both audio drivers?

**Comment by Alucard648** [comment]
Just did a completely fresh reinstall of PGE and all signs of lag are gone. Sorry for potential false alarm. Closing now.
Here is the info of my sound driver.
![sound_driver](https://user-images.githubusercontent.com/7596025/41005537-99b2b318-6926-11e8-8bd1-36feba38af21.png)
Keep up with the project.

**Comment by Wohlstand** [comment]
Anyway, this issue has been reproduced on my girlfriends's computer... After some analyzes, I have found that 32-bit build is not able to use DirectSound output even I forcing it to use it... It's a bug which was caused probably by the wrong MinGW toolchain where SDL2 was built on AppVeyor ci... It's probably another issue which I'll create separately.
