### ISSUE TITLE
[Windows Online Installer] Fails to auto-detect between 32-bit and 64-bit systems.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#254]
**Which component?**
-PGE Online installer

**Describe the bug**
Online installer failed to detect architecture of CPU installed in my PC (32-bit or 64-bit) and, in my situation, installed 32-bit build  on my 64 bit PC. Here are specs of my PC.
![system_specs](https://user-images.githubusercontent.com/7596025/40998784-7425def0-6911-11e8-879c-e1dc511661c8.png)

**To Reproduce**
1. Run PGE online installer on 64-bit and 32-bit machines.

**Expected behavior**
Online installer should install 32-bit build on 32-bit machine and 64-bit version on 64-bit machine.

**Screenshots**

**Desktop specs (please complete the following information):**
Windows 7 SP1

**Comment by Wohlstand** [comment]
That very weird... Did you ran the installer through any compatibility modes or you have ran it in a default state?

**Comment by Alucard648** [comment]
Installer was run in default state, just by double-clicking on it.

**Comment by Alucard648** [comment]
Tried again. Auto-detect worked fine. Sorry for disturbing. :-(  Closing now.
And last, but not least, keep going with PGE Project! The future of fangaming is in your hands...

**Comment by Wohlstand** [comment]
Thanks :fox_face: :+1:
