### ISSUE TITLE
[Online Installer] Include Timidity&SNES-like sound bank into PGE Project package

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#256]
Every time I do fresh installation of PGE, I always end up missing TiMidity and SNES-like sound bank. The missing MIDI device is listed as available in PGEMusplay, but on attempt to play a MIDI file with this option, I got this message:
![timidity](https://user-images.githubusercontent.com/7596025/41006780-a572fe92-692b-11e8-8276-e34bbc015d09.png)
This error can be fixed by putting missing folder into main PGE Project directory. This bank is found here:
https://yadi.sk/d/bky-syShwpTRH

**Describe the solution you'd like**
Include TiMidity and SNES-like sound bank into installation and portable PGE project builds.

**Comment by Alucard648** [comment]
Ok. The main issue is gone. As for built-in playable episode, I could better include original The Invasion II that was bundled with SMBX 1.3.1, not the unfinished monstrosity

**Comment by Wohlstand** [comment]
I wasn't included "The invasion" or "The invasion 2" by the reason as there are well known and not so interested for most of SMBX users except of nostalgic repay. However, I still keep my modded "The Invasion" where I have used "SMB Redrawn" graphics with some mix of community graphics, A2XT and custom music and sound packs. About of "LC Demo", I have to upgrade it with "LC Beta" I need to mod (Re-Apply my music replacements). But a good idea to ship "Invasion"s with the "SMBX 1.3" config pack
