### ISSUE TITLE
[SDL2 Mixer X] Numerous player crashes 

### ISSUE THREAD

**Issue by papiezak** [WohlSoft/PGE-Project#265]
SDL2 Mixer X + PGE MusPlay, commit  47ea8f6 

Upon loading any MIDI file, PGE MusPlay is stuck on Native OS MIDI device, attempt to change it results in an instant crash.
Stopping the playback results in same thing (pausing the song doesn't cause any crash, though)
WAV recording also crashes the player.

OS is Windows 10 x64, both 32-bit and 64-bit builds of PGE MusPlay exhibit the same unstable behaviour.

GDB reports a segmentation fault (32bit build):
![segfault pge](https://user-images.githubusercontent.com/32672779/44041750-d02491c2-9f1e-11e8-9ecb-4de26e011f8a.PNG)

![segfault 2](https://user-images.githubusercontent.com/32672779/44042911-d391babc-9f21-11e8-95f9-cfd4745a1919.PNG)

**Comment by Wohlstand** [comment]
Yesterday I have tried PGE MusPlay on NativeMidi and attempt to switch into any other MIDI player have caused sudden crash, on Windows 7, so, thank for remembering me to fix this crap...

**Comment by Wohlstand** [comment]
Fixed!
https://github.com/WohlSoft/PGE-Project/commit/56982bda8920bfe93daf6c5497d5438f9050eefb
https://github.com/WohlSoft/SDL-Mixer-X/commit/22431eb24f32e46a7780e59e5b2d55c5971fed4b
It was a tiny fix. Please test the whole stuff when everything will be built.

**Comment by papiezak** [comment]
Yes, no more crashes so looks like it's fixed. Thanks!

**Comment by jadasse** [comment]
it doesn't work anymore
