### ISSUE TITLE
[PGE-Help] Port entire manual into Docute.js with Markdown

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/PGE-Project#282]
# For now, the current documentation state is a one big mess:
* It's hard to edit it with having no full featured WYSIWIG editor
* Hard to maintain
* Hard to proofread and apply quick edits by anyone

# Reasons to use docute framework and markdown files:
* Markdown files are portable and more lightweight
* Markdown files can be easily edited from absolutely any text editor without having troubles like with a case of complex and heavy HTML
* Markdown files can be easily edited by non-experient users with no necessary to hack HTML for simple tasks.

**Framework itself:** https://v3.docute.org/#/
**A documentation example made with this framework:** https://github.com/JuniperBot/Documentation

# To do:

- [x] Convert all HTML files (about 82 files) into Markdown
- [x] Create the overlay that will handle those markdowns
- [x] Put the standalone docute build for standalone documentation use
  * clone Docute repository
  * run `yarn add dependencies` to fetch dependent packages
  * run `yarn build` to compile the docute
  * copy `dist` and `lib` folders, and `package.json`, `LICENSE`, and `README.md` into the local subfolder
  * In the Docute 4 html sample, replace `unpkg.com` links with relatives
- ~~[ ] Create the remote viewer to allow everyone see the documentation in real time directly from GitHub's store~~ (~~[the example](https://github.com/JuniperBot/Documentation/blob/master/website/remote.html)~~, ~~[this is that alive](https://docs.juniperbot.ru/)~~, both dead, sad...) **No longer needed: CI will deploy the documentation every commit.**

**Comment by Wohlstand** [comment]
Experimental branch was made in this night: https://github.com/WohlSoft/PGE-Editor-Help/tree/docute

**Comment by Alucard648** [comment]
> * [ ]  Create the remote viewer to allow everyone see the documentation in real time directly from GitHub's store ([the example](https://github.com/JuniperBot/Documentation/blob/master/website/remote.html))

Example page link yields 404 not found.

**Comment by Wohlstand** [comment]
> Example page link yields 404 not found.

Yeah, because @GoldRenard have nuked it recently and reorganized his repo to use WebPack. However, the full working documentation sample you can see here: https://docs.juniperbot.ru/

**Comment by Wohlstand** [comment]
Adding the life preview of a current state of documentations upgrade https://wohlsoft.ru/editorhelp/manual_editor_new.html#/

**Comment by Wohlstand** [comment]
I think, there are all documents has been ported completely. A big thanks to the @mlloewen and @Core-LOVE for the small help with such a long process!
Anyway, instead of the remote viewer, I'll leave the just simple CI that does packing and uploading of the documentation to the server.

**Comment by Wohlstand** [comment]
I solemnly announce this issue of 2018 year completely solved!

The work on any missing and incomplete pages will be done at issue #228.
