### ISSUE TITLE
[Editor] LunaTester crashing on attempt to re-run test while lua-side dialog boxes are shown

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/PGE-Project#283]
> @Hoeloe: LunaTester is just crashing, but that any dialog window, whether from windowDebug or a lua error, causes LunaTester to crash IF PGE tries to reload the level

In a moment when LunaLua-SMBX is ran and has shown up any additional GUI dialogs (debug box, error message, etc.), attempt to re-run the test on the fly (requesting the test of level from the editor), the LunaTester gets a crash.

**Note:** The bug is reproducing in latest PGE Editor assembly, but doesn't happen in older.

**Comment by Wohlstand** [comment]
Okay, it's the more detailed information:
* The "LunaTester crashing" is meant the LunaLua crashed, not PGE Editor (as LunaTester is the embedded part of PGE Editor, then, crash of LunaTester will also crash PGE Editor).
* This crash is also reproducing on latest LunaLua

How to reproduce:
* Open a dialog window via `Text.windowDebug(string debugText)` lua call from LunaLua
* Do not close it
* Go back to PGE
* Open "Test" -> "LunaTester" -> "Test level" menu item
* Then, close the opened dialog window on LunaLua that still running

**Comment by LoveBodhi** [comment]
LunaLua-SMBX is no longer supported anymore

**Comment by Alucard648** [comment]
And how you would want to test levels made with PGE editor without painstakingly reloading them in legacy SMBX editor? As far as I can tell, the only way to do this is to open them in SMBX2.

**Comment by Wohlstand** [comment]
@LoveBodhi , the LunaLua-SMBX is the core, it's still supported, but doesn't producing as standalone package

**Comment by Wohlstand** [comment]
Some weeks ago LunaTester got a major rework. It needs to verify this thing again to be sure does it's reproducable now, or problem has gone away?

**Comment by Bluenaxela** [comment]
This no longer crashes. Test mode won't restart until the dialog box is closed, but that seems fine and it works cleanly.
