### ISSUE TITLE
[Editor] Search -> Select All

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#287]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it`s needed to perform an operation on items that match specific crieria across the whole section or level, only to be able to do this on per item basis resulting in time-consuming and sometimes error-prone affair. For examples:
1. Move all enemies of specific ID.
2. Assign all purple coins in level to separate layer and set "layer empty" event slot to event that triggers reward.
3. Just check out layer contents to ensure it is correct to quickly fix/avoid show stopping bugs, whose culprit is objects being on wrong layer.

4.And many more ways to automate routinious processes in level design. 

**Describe the solution you'd like**
An option for search engine to set selection to all items that match search query and remove selection to other items..

**Comment by Wohlstand** [comment]
A recent WIP thing that works:
![Peek 2020-05-15 00-59](https://user-images.githubusercontent.com/6751442/81990286-8c5d7180-9647-11ea-952d-07ff0ee0964f.gif)

**Comment by Wohlstand** [comment]
Okay, just now I sent the set of changes which fully implements this on both level and world map.

**Comment by Alucard648** [comment]
Download fails dueto timeout.

**Comment by Alucard648** [comment]
Works as intended and suggested. Thanks.

**Comment by Wohlstand** [comment]
Okay, closing this as complete task.
If any future bugs will appear, fix them independently.
