### ISSUE TITLE
Some windows out of the reaching boudary after Super Mario Bros. X. 2 Upgrade

### ISSUE THREAD

**Issue by dudwitsen203** [WohlSoft/PGE-Project#293]
Opetaring System: Windows 10
Issue: Windows deformed out of reach
How it happen: I upgrade Super Mario Bros. X. 2 to latest version. Open PGE now i click item seletcor the window does not appear in the screnn.
Sorry for bad english.

**Comment by Wohlstand** [comment]
Close editor
Remove `data/PGE/settings/pge_editor.ini` file. It's junk file that came with an installer. It must never be deployed in public installation, it's local computer settings file only

**Comment by dudwitsen203** [comment]
You sure won't broke registery?

**Comment by Wohlstand** [comment]
Lol :grin: 
Do you really think the deletion of one silly INI file will break a system database of the operating system called a registry? :rofl: 
PGE apps never using the registry for their settings, they are saving all settings into INI files. That means, you can pick-up PGE installation into a USB stick and travel between different computers and use your settings. So, feel free to remove this broken settings file, and Editor will get all defaults, include initial positions of toolboxes.

**Comment by Wohlstand** [comment]
```
it's local computer settings file only
```
I meant, this file contains your personal settings of Editor: position of toolboxes, toggled settings, recent files, recently opened paths, they are all include absolute paths to your home folders. Transferring this file between different computer is a bad idea: settings will not fit into different computer, mainly, when computer has different screen sizes, etc. Default settings of Editor are all calculating directly from an actual size of screen.

**Comment by dudwitsen203** [comment]
I delete it. What now

**Comment by Wohlstand** [comment]
Start Editor again :fox_face:

**Comment by Wohlstand** [comment]
(note that you should delete the file in only condition when Editor is closed, otherwise, Editor does saving of setup on quit, and your deletion will be useless)

**Comment by dudwitsen203** [comment]
What you mean?

**Comment by Wohlstand** [comment]
I mean next: to correctly fix your trouble, you need to do next:
- close Editor completely
- remove settings file
- start Editor back

What will happen if you will delete a file while Editor is running? The broken file will appear again! Why? The editor does the loading of settings on startup and does saving on closing. So, Editor has loaded broken setup, and it will save it back on close.

**Comment by dudwitsen203** [comment]
I delete it again after closeing the game?

**Comment by Wohlstand** [comment]
Not game, Editor. Delete it once when the editor is NOT running. And try to start the Editor again.

**Comment by Wohlstand** [comment]
Once Editor works fine, no more need to do anything.

**Comment by Wohlstand** [comment]
P.S. what your native language,

**Comment by dudwitsen203** [comment]
My windows appear back? Why had to delete it?

**Comment by Wohlstand** [comment]
> My windows appear back? Why had to delete it?

Yes, your windows must appear back. The settings file which came with an installer shipped a wrong position of windows. It's a reason why they are out of the screen. When you removing settings file, you are resetting PGE Editor's settings into a default state, include positions of windows are must appear back.

**Comment by Wohlstand** [comment]
So, if your windows appeared back, please tell me to confirm that it's fine now.

**Comment by Wohlstand** [comment]
Okay, another question: how many monitors you have plugged?

**Comment by dudwitsen203** [comment]
Thanks you very much, can see the windows now

**Comment by Wohlstand** [comment]
I'm glad that this works now :fox_face:
