### ISSUE TITLE
xmi playing as dosbox does

### ISSUE THREAD

**Issue by alexeik** [WohlSoft/PGE-Project#294]
Please maybe is it possible to emualate? to dump xmi files to wav with nostalgia.

**Comment by Wohlstand** [comment]
You can use libADLMIDI for that: https://github com/Wohlstand/libADLMIDI .
Compile it with enabling of MIDIPLAY tool and then, you'll be able to directly convert any MIDI file into WAV quickly. The libADLMIDI synthesizer is used in PGE as one of MIDI synthesizers together with libOPNMIDI and others.

**Comment by Wohlstand** [comment]
One note: for your XMI you'll also have AD and OPL banks. To use them in libADLMIDI as side-load, please convert any of these banks into WOPL format. Here is a luck if your bank is already in a set of embedded libADLMIDI's banks

**Comment by alexeik** [comment]
can we talk on russian?

**Comment by Wohlstand** [comment]
Да конечно же! :fox_face: Зачем мучиться и говорить на чужом языке, когда можно спокойно на своём :stuck_out_tongue_winking_eye:

**Comment by alexeik** [comment]
:) 
Слушай, да прикольно, что тут наши из города резинового.
Я тут делаю мод для openra платформы на дюну2.
ВОт пришел к тому, что нету софтовых эмуляторов с такой же эмуляцией как dosbox.
хожу уже спрашиваю, кто может чем помочь.

мне нужно прогнать через софт аналогичный dosbox, но еще и дамп сделать этой xmi
с твоей библиотекой , мне не понятно, как про AD & OPL банки.
и вообще как достичь результата)
я PGE music player то поставил не сразу, притом что сам программер.

**Comment by Wohlstand** [comment]
Ну так libADLMIDI использует DosBox-овский эмулятор под капотом как один из, также он использует эмулятор Nuked OPL3, который максимально точно эмулирует OPL3-чип. Будет звучать не только как DosBox, но и даже лучше - как реальный OPL3-чип!

Кстати, лучше таки перемещю задачу прямо в libADLMIDI-шную репу, там как раз по теме будет.

**Comment by alexeik** [comment]
Тогда помоги:)
у меня среды для компиляции нету в windows 7.
я даже в банках не разбираюсь.
может, что скажешь по этой xmi приложу ее сюда.
чтобы просвятить меня.

https://youtu.be/FEF-Nk025-c
вот как выглядят разные проигрышы.  в этом видео два видоса.
первая часть OPL , меня интересует. это запись с dosbox сделана.

[dune0.zip](https://github.com/WohlSoft/PGE-Project/files/3595525/dune0.zip)

**Comment by Wohlstand** [comment]
У тебя мультидорожный XMI-файл, т.е. в одном файле запаковано несколько мелодий одновременно, мне придётся его засколоть на части для начала через XMI2MIDI...

**Comment by alexeik** [comment]
это не важно, про много дорожек.
я и сам поколоть могу.
дело в звуке.

**Comment by Wohlstand** [comment]
Покопал, нашёл, что кроме XMI, есть ещё формат ADL:
http://www.shikadi.net/moddingwiki/ADL_Format
Это, скорее всего, что-то близкое к IMF, который представляет из себя цепочку OPL-регистров, последовательно отправляемых на чип. А тут я нашёл полный пакет всей музыки к игре: http://www.vgmpf.com/Wiki/index.php/Dune_II:_The_Building_of_a_Dynasty_(DOS)

**Comment by alexeik** [comment]
Тут понимаешь, та ссылка на уже оцифрованные,это известная штука)
Но там только 3хх подобны dosbox ,но они отличаются!
это видно на примере introduction музыки.
ADL в дюне2 тоже есть, там 4 формата миди под разные железки лежат. 
`alfx.drv	 
algdig.adv	 
dune0.adl	 
dune0.c55	 
dune0.pcs	 
dune0.tan	 
dune0.xmi	 
dune1.adl	 
dune1.c55	 
dune1.pcs	 
dune1.tan	 
dune1.xmi	 
dune10.adl	 
dune10.c55	 
dune10.pcs	 
dune10.tan	 
dune10.xmi	 
dune11.adl	 
dune11.c55	 
dune11.pcs	 
dune11.tan	 
dune11.xmi	 
dune12.adl	 
dune12.c55	 
dune12.pcs	 
dune12.tan	 
dune12.xmi	 
dune13.adl	 
dune13.c55	 
dune13.pcs	 
dune13.tan	 
dune13.xmi	 
dune14.adl	 
dune14.c55	 
dune14.pcs	 
dune14.tan	 
dune14.xmi	 
dune15.adl	 
dune15.c55	 
dune15.pcs	 
dune15.tan	 
dune15.xmi	 
dune16.adl	 
dune16.c55	 
dune16.pcs	 
dune16.tan	 
dune16.xmi	 
dune17.adl	 
dune17.c55	 
dune17.pcs	 
dune17.tan	 
dune17.xmi	 
dune18.adl	 
dune18.c55	 
dune18.pcs	 
dune18.tan	 
dune18.xmi	 
dune19.adl	 
dune19.c55	 
dune19.pcs	 
dune19.tan	 
dune19.xmi	 
dune2.adl	 
dune2.c55	 
dune2.pcs	 
dune2.tan	 
dune2.xmi	 
dune20.adl	 
dune20.c55	 
dune20.pcs	 
dune20.tan	 
dune20.xmi	 
dune3.adl	 
dune3.c55	 
dune3.pcs	 
dune3.tan	 
dune3.xmi	 
dune4.adl	 
dune4.c55	 
dune4.pcs	 
dune4.tan	 
dune4.xmi	 
dune5.adl	 
dune5.c55	 
dune5.pcs	 
dune5.tan	 
dune5.xmi	 
dune6.adl	 
dune6.c55	 
dune6.pcs	 
dune6.tan	 
dune6.xmi	 
dune7.adl	 
dune7.c55	 
dune7.pcs	 
dune7.tan	 
dune7.xmi	 
dune8.adl	 
dune8.c55	 
dune8.pcs	 
dune8.tan	 
dune8.xmi	 
dune9.adl	 
dune9.c55	 
dune9.pcs	 
dune9.tan	 
dune9.xmi	 
duneinit.xmi	 
mt32mpu.adv	 
pasdig.adv	 
pcsound.drv	 
pcspkr.adv	 
sbdig.adv	 
sbpdig.adv	 
tandy.adv`

Вот содержимое папки со звуками. Даже 5 форматов одного и того же.

**Comment by Wohlstand** [comment]
> ADL это для железок ADLIB сделано.
> dosbox же делает это через FM-синтез через эмуляцию OPL.

Лол! :rofl: 
AdLib это ПЕРВАЯ карта на FM-синтезе, и которая использует чип OPL2. Первые SoundBlaster тоже использовали OPL2, но потом они стали использовать OPL3 (начиная с SoundBlaster Pro).

**Comment by alexeik** [comment]
GameRip тоже проверял. там Inroduuction тоже не тот, как в dosbox.

**Comment by Wohlstand** [comment]
Чипы OPL2 и OPL3 совместимы между собой, OPL3 отличается дополнительными фичами и новыми режимами работы, а так, полностью идентичен чипу OPL2. У меня самого SB16 был, и он же есть. А так, пока спеки на ADL-файлы нету, попробую сделать кое-какой хак и получить WOPL-банк, на котором всё будет звучать как надо :fox_face: :wink:

**Comment by alexeik** [comment]
То есть , ты отталкиваешься именно от ADL файлов?
Я думал от XMI.

**Comment by Wohlstand** [comment]
XMI это всего лишь ноты, FM-инструментов не содержат. Обычно для XMI-файлов FM-инструменты лежат в файлах AD или OPL, а именно в этой игре они поместили их в ADL-файлы, которые вовсе не похожи на то, что использовалось в библиотеке AIL (аудиобиблиотека, от которой и пошли XMI-файлы).

**Comment by alexeik** [comment]
Ого, спасибо за подробности!

**Comment by Wohlstand** [comment]
PGE-Project это он и есть, в комплекте тут, в этом проекте, в папке `Engine` :fox_face:

**Comment by alexeik** [comment]
Получаетя, что нету дампов музыки в формате OPL в свободном доступе?
я тут на vogons пообщался с хозяином. Он просвятил в xmi формате, что это для MT-32 синтезаторов.Поэтому я и не мог из этих xmi получить , ТО что слышу в DOSBOX.

**Comment by Wohlstand** [comment]
Давай продолжать беседу здесь: https://github.com/Wohlstand/OPL3BankEditor/issues/158
Ибо первым делом такие вещи больше относятся к libADLMIDI и OPL3-BE, а PGE-Project это лишь проект, который использует libADLMIDI в составе, но задача сама относится именно к самому libADLMIDI, который и есть ядро проигрывания музыки на OPL3-чипе, и к OPL3-BE как к редактору, который способен работать с такими инструментами.

**Comment by Wohlstand** [comment]
> adlib.zip
Попробую-ка прикрутить эту штуку к libADLMIDI и посмотрим, как он будет исполнять музыку в них...

**Comment by alexeik** [comment]
Смотрел уже целые сутки на этот C++ код.
Чтото магии много стало в С++. 
Трюк с этим:
`
 memset(buf + bufSize - 1024, 0, 1024);

    SoundAdlibPC::callback(this, buf + bufSize - 1024, 1024);

    bSilent = true;
`
Не понятен. Этот callback уходит в такие дали, что даже код не понятно как читать.

**Comment by Wohlstand** [comment]
Закрываю, т.к. эта задача по факту относится к другому проекту/зависимости, и ни как не соотносится с самим PGE-проектом.

Closing as this issue in fact is related to different project/dependency and can't be affiliated with PGE-Project itself.
