### ISSUE TITLE
[Editor] Change text color in developer console

### ISSUE THREAD

**Issue by NathanBnm** [WohlSoft/PGE-Project#305]
It's just a detail but I think we have to change the text color in the developer console. Lightgreen makes the text difficult to read. Maybe you could use a darker green or black.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/45366162/67418554-45386200-f5cb-11e9-8c56-e16ba12f5f7b.png)

**Comment by Wohlstand** [comment]
Whops... The background should be black. No idea why it's white... :thinking:  Looks like a bug.
Anyway yeah, here is should be an ability to tune colors of the whole thing here... Thanks for the notice. :fox_face: :+1:

**Comment by Wohlstand** [comment]
What's inside of it:
![Снимок экрана_2019-10-23_23-21-31](https://user-images.githubusercontent.com/6751442/67430899-dcadad00-f5eb-11e9-8143-e6ddcff9123e.png)
The black color and green text are hardcoded here. As a solution for some cases, I can simply drop the colorization from here at all to prefer the system colors without a custom colorization. Or I'll just check them out for the reason why on your end the black color was didn't apply. 

Anyway, a small trivia: Windows 10 is so odd platform where are lots of random bugs happen, and some of bugs are affecting my apps too, so, then I needed to boot up my Win10 VM (that I using very rare) to debug this weak case and fix it if it's possible...

**Comment by Wohlstand** [comment]
Okay, I did a small tweak to disable colorization of dev-console on Windows 10 because native UI rejects any customizations like this I trying to do, unfortunately. However, it's possible to escape this bug with toggling of Fusion style to be used instead of Winodws native.

**Comment by Wohlstand** [comment]
Okay, my friend had to test this and confirmed a fix.
