### ISSUE TITLE
Remove ALL Traces of "Mario" from this Project

### ISSUE THREAD

**Issue by mario2582** [WohlSoft/PGE-Project#334]
**Remove ALL Traces of "Mario" from this Project or get SUED by NINTENDO,**

_**I HAVE REPORTED THIS GITHUB PAGE TO LAWYERS OF NINTENDO OF AMERICA!!!**_

**Comment by Wohlstand** [comment]
1) This project doesn't intend to use for Mario, here are tech stuff only
2) NOA is out of my jurisdiction
3) Lol, the best trolling of the universe :smile_cat: :fox_face:
