### ISSUE TITLE
[Editor] Dark Theme/Color Theme Selection

### ISSUE THREAD

**Issue by Emral** [WohlSoft/PGE-Project#337]
**Is your feature request related to a problem? Please describe.**
90% of apps in the modern world have dark themes. I created a little mockup, but there are a few quirks I don't know how to sort out.
https://cdn.discordapp.com/attachments/217791747495821312/681087538487754773/unknown.png

**Describe the solution you'd like**
Currently the editor has no support for any different stylings. It has "Themes", but those are icon themes. For proper color-themes, the following needs to happen:
- Drop-down in the settings menu for color theme selection
- Native configuration of additional themes

However, there are a few hurdles regarding the configuration of additional themes:
- Non-white styling of the Qt::Horizontal control and the border around the level window
- Fixing the Background Image Selector for the "Fusion" theme used in the screenshot
- Fixing the "extra settings" display for the "Fusion" theme used in the screenshot
- Config packs must be able to optionally define dark versions of icons (see: grid icon, lock icons)

**Describe alternatives you've considered**
With so many hurdles in using the platform-independent "Fusion" theme, it sounds like omitting that step would make things easier. I have considered this, but doing so is a platform-specific nightmare, with various Windows controls refusing to be styled at all:
https://cdn.discordapp.com/attachments/219163581596303370/681082138698973214/unknown.png

**Additional context**
I have pushed my experiments to the fusiontheme branch on the repository. These experiments override the default style at load time.

#savetheeyes

**Comment by Wohlstand** [comment]
Speaking about themes, even a good example - Qt Creator, which now have a flexible color themes system, maybe copy paste some code from it? About palletes, I would to make the separated class that should construct a necessary pallete in dependent from an app settings state, and send that into main window's instance. I'll try to review this tomorrow after sleep.
About combobox with images in Fusion theme, I know this issue for many years, and the solution is building own bg selection thing, I even has the wip thing in a separate branch which I didn't complete yet in favor of more important tasks at that moment. Maybe revive it?

**Comment by Emral** [comment]
I couldn't get the project to run in Qt Creator so I worked completely isolated in Visual Studio Code, without a visual view. Didn't know about the WIP bg selection thing, that's pretty rad! If you're looking for any visual style references for that one, I suggest not treading too far from what we already have, since it's already pretty good. For comparison: here is how the Unreal Engine handles many of its asset context menus: https://forums.unrealengine.com/filedata/fetch?id=1678710&d=1572196510

**Comment by Wohlstand** [comment]
> isolated in Visual Studio Code, without a visual view

It's absolutely possible to work with any IDE you want, that just can handle the CMake projects build.

btw, the dark theme of Qt Creator I like to use (on aborad there are some multiple themes, and it's one of them only):
![Снимок экрана от 2020-02-24 18-37-32](https://user-images.githubusercontent.com/6751442/75167373-4f639c00-5736-11ea-854d-8fa585198048.png)

> Config packs must be able to optionally define dark versions of icons (see: grid icon, lock icons)

If these UI themes going be hardcoded, not just one another external INI files to tune them (but it's really possible to craft them, however, some cases I would to ship as hardcoded), then, I'll extend the "theme.ini" with adding the mirrors of existing arguments with specifying of a theme suffix to allow alter icon in a specific from a color scheme, or just fall back into "common" version which is used by default.

> For comparison: here is how the Unreal Engine handles many of its asset context menus: https://forums.unrealengine.com/filedata/fetch?id=1678710&d=1572196510
As you can see, it's very similar to the one in the editor.

I think instead of tweaking the combo box's pop-up menu as I did in that branch (result works, but it's clunky and hard-controllable), I would to craft a new widget for this and make a different pop-up dialog which will be much more.

**Comment by Wohlstand** [comment]
Just now I have been imported master's changes into your branch and I gonna craft a class to manage color styles together with themes mechanism...

**Comment by Wohlstand** [comment]
This one needs an own custom widget to be not buggy anymore here...
![Снимок экрана_2020-02-27_00-58-11](https://user-images.githubusercontent.com/6751442/75392052-4fad9400-58fc-11ea-88a5-6e3746f381ca.png)

**Comment by Wohlstand** [comment]
I forgot to tell that this background selector is even worse on macOS, another reason why I should craft a custom widget for it.

**Comment by Wohlstand** [comment]
Okay, meet a skeleton for a new image selection widget, here I did two classes:
- A widget itself just puts on self a QPushButton (maybe make something another instead?) and sets QLayout to insert a button into self
- A QDialog-based frameless widget made as a custom menu
- Over this skeleton is possible to craft anything cool and much better than just QListWidget crap used inside of standard QComboBox's menu.
![Peek 2020-02-27 01-51](https://user-images.githubusercontent.com/6751442/75395525-ac607d00-5903-11ea-912e-1d7ee82b4237.gif)

**Comment by Wohlstand** [comment]
![Peek 2020-02-27 02-17](https://user-images.githubusercontent.com/6751442/75397282-850baf00-5907-11ea-80d0-fb3f077fa9d0.gif)

**Comment by Wohlstand** [comment]
I'll continue the thing tomorrow, now I gonna to sleep.

**Comment by Wohlstand** [comment]
Going to resume a work of this task tomorrow at the evening (after my work time). Until to take this for aboard and make the ability to toggle UI themes (between Native, Fusion, Custom/dark pallet, etc.), I need to complete the work on a background selector box as a custom widget to make it being fully controllable (while this sucks on Fusion theme, on macOS we can see a much worse case...).

**Comment by Wohlstand** [comment]
It gets being more closed:
![Peek 2020-07-06 01-35](https://user-images.githubusercontent.com/6751442/86543678-96a23a80-bf29-11ea-8f77-f53552ec4581.gif)

**Comment by Wohlstand** [comment]
Okay, at first I'll leave the most basic implementation as-is, without extras, it just works:
![Peek_2020-07-22_00-45](https://user-images.githubusercontent.com/6751442/88144923-55d14380-cc02-11ea-8c87-7f537e7f8c9f.gif)
(extending it with features like changing order and search filter can be made later, not now).

So, the next step is starting the experiment with a dark theme and style switching ability directly.

**Comment by Wohlstand** [comment]
Okay, I had to add the blank title bar with a close button and I made the menu being a modal dialog to prevent users from making stupid actions with causing a confusion:
![Peek 2020-07-22 22-56](https://user-images.githubusercontent.com/6751442/88226352-9f5a7680-cc74-11ea-9429-f534cf65bcfd.gif)

However, by @Bluenaxela 's review, this maybe being a little annoying. It's better to make it being automatically hidden when clicking outside, however, it's tricky to make that, and I left this for a future as a less important.

The quote:
> Hm... I could see that change maybe being a little annoying. Yes it allows it to be resizable, but I have real doubts that being resizable is useful. Being bigger to see more at once doesn't nessarially help so much since the eye needs to scan around more anyway, and being a consistent size always is good for a user getting used to where thing are, which I think it more helpful. Also I can imagine many moments of a user who is used to just clicking outside of what comes up when clicking a dropdown, trying to click outside of this modal window to cancel, but it won't work because it's modal and they need to click the x instead which is less convenient. At very least I think it would be better to make it close when unfocused instead of making it modal.

So, I had to merge this into the Master, and I am free to begin the main work with color themes now.

**Comment by Wohlstand** [comment]
PERFECT! It no longer glitches:
![Снимок экрана_2020-07-23_00-11-07](https://user-images.githubusercontent.com/6751442/88229201-0712c080-cc79-11ea-8d05-1d454bfa1371.png)

So, tomorrow I'll continue the main work.

**Comment by Wohlstand** [comment]
I saw the mention of that extra settings needs some tuning, what I see now:
![Снимок экрана от 2020-07-26 00-21-18](https://user-images.githubusercontent.com/6751442/88466526-fb700580-ced5-11ea-9dc5-9441706ef637.png)

looks like it works correctly. Maybe it didn't work with a previous shitty [QtPropertyBrowser](https://github.com/WohlSoft/QtPropertyBrowser)? I had to replace it with a hand-made widget that is much more controllable and handy, and simplier internally. The great help of C++11 with lambda-calls are ULTRA-useful.

**Comment by Wohlstand** [comment]
About dark version of icons I had to implement:
(built-in icons will work, I need to make the same for section switch buttons are still show the black).

![Снимок экрана от 2020-07-26 00-25-45](https://user-images.githubusercontent.com/6751442/88466598-9963d000-ced6-11ea-9b63-20b482cfb827.png)

The one thing of behavior for the case when custom icon was loaded but no dark version is given:
* When the main version of the icon was given, but the dark icon didn't customize, show the default dark icon
* When the main version of the icon was given, but the dark icon didn't customize, show the customized main icon only

I think, the second behavior looks better, especially it will don't confuse with a sudden appearance of built-in icon when theme has it being customized.

**Comment by Wohlstand** [comment]
Okay, here is some tasks list to continue the work:
- [ ] Make dark versions of section number built-in icons
- [ ] Fix the `Non-white styling of the Qt::Horizontal control and the border around the level window`
- [ ] Fix the restoring the default built-in palette when choosing "Default" palette in the application settings (that doesn't work yet)
- [ ] Fix the restoring of the default style (GTK or Windows) when choosing the "Default" palette in the application settings, or, alternatively, notify with the fact the application must be restarted to apply changes.

**Comment by Wohlstand** [comment]
Built-in section number icons friendly with a dark palette:
![Снимок экрана_2020-07-26_16-58-40](https://user-images.githubusercontent.com/6751442/88480895-53078300-cf61-11ea-9f2c-3b2700ae3be3.png)

**Comment by Wohlstand** [comment]
About themes: every icon and image entry now has the analog with a `-dark` suffix that gives an ability to give the alternative version of icon for a dark palette mode. I will need to specify that.

**Comment by Wohlstand** [comment]
Okay, I think, I'll merge the current state into the master for a public preview/testing. If something will be needed, I'll leave the "Known bugs" paragraph.

So, what I did:
* I had to extend the Themes (Editor/common_features/themes.cpp) code to add the basic palettes system.
* I moved your palette into Themes class. So, if you want to tune some after, feel free, you will find your palette at `Editor/common_features/themes.cpp`.

**Comment by Wohlstand** [comment]
@Emral, If anything will be needed, let me know.

**Comment by Alucard648** [comment]
Close button on open document tab is almost invisible.
![invisible](https://user-images.githubusercontent.com/7596025/88492118-14011e00-cfb1-11ea-8513-f3fca944674c.png)
Try to find it.

**Comment by Wohlstand** [comment]
That right, however,  idk how to customize it. I need to check the possibility of that...

**Comment by Wohlstand** [comment]
Probably, something like can be used as an attempt: https://forum.qt.io/topic/50088/solved-customize-qmdiarea-qtabbar/2

**Comment by Wohlstand** [comment]
However, built-in Qt Creator's dark palette literally makes the lighter cross icon:
![Снимок экрана от 2020-07-27 15-17-48](https://user-images.githubusercontent.com/6751442/88540846-64fa2c00-d01c-11ea-80f0-cd9eed5f2bb6.png)
