### ISSUE TITLE
[Editor] Can't redo after undoing the objects pasting

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/PGE-Project#379]
A bug reported at the Discord

> **Taycamgame#5382**
weird bug:
if you copy an object
and then, if you paste it somewhere
all good so far, right?
Now, if you undo the action
the object you pasted is now gone, right?
But what happens if you redo the action? the object should reappear where it was right?
well... sort of. Except it gets offset when it reappears.

**Comment by Alucard648** [comment]
Tried to reproduce this bug. Here is what I found:
1. We copy an object or a set of objects.
2. We paste stuff into new place. It snaps to grid as intended.
3. Undo And Redo - and copied objects reappear in exact place the mouse was clicked when original action was recorded in editor history, disregarding grid snapping, hence reappearing out of place.

**Comment by Wohlstand** [comment]
Just now I fixed this bug, so, you can test the work of a thing.

**Comment by Alucard648** [comment]
Works like magig.

**Comment by Wohlstand** [comment]
Perfect! So, closing this now!
