### ISSUE TITLE
[Editor] Wine dont open SMBX 38A.exe

### ISSUE THREAD

**Issue by M0REKZ** [WohlSoft/PGE-Project#382]
maybe i am doing something wrong..

im using custom smbx.exe path but the path to wine is "System Default"

the level i want to play is https://wohlsoft.ru/forum/viewtopic.php?f=60&t=3265

please help

**Comment by Wohlstand** [comment]
Please enable Wine logs and show the console (help -> show development console). Wine should print the reason why game won't start.

**Comment by Wohlstand** [comment]
btw: unlike others, this game REQUIRES the hardware acceleration being accessible (because of DirectX9), and it won't work at all if hardware acceleration doesn't work at all.

**Comment by M0REKZ** [comment]
> Please enable Wine logs and show the console (help -> show development console). Wine should print the reason why game won't start.

development console:

(replaced username)

Orig Path /Users/name/Desktop/Info/wine/SMBX 38A/worlds/Castle Raven/Castle Raven -> /Users/name/.wine/drive_c/windows/temp/38a-lvl-test/___smbx38a-temp-level.lvl
SMBX-38A: starting command: /Users/name/Library/Application Support/PGE Project/wine /Users/name/Desktop/Info/wine/SMBX 38A/smbx.exe  0 1 1 %53%4D%42%58%41%72%67%73%7C%32%30%2C%30%2C%30%7C%31%2C%30%2C%31%2C%30%7C%2C%30%2C%30

enabled Wine debug printing too on "Wine Settings"

**Comment by Wohlstand** [comment]
> /Users/name/Library/Application Support/PGE Project/wine

Looks like you have no installed Wine, or you need to tune it, set up its paths manually from the "Wine settings...". You also can use the PlayOnMac thing to make the game work. Editor is able to import POM configuration to point a necessary setup of Wine.

**Comment by M0REKZ** [comment]
SMBX-38A: starting command: /Applications/Wine Stable.app/Contents/MacOS/wine/bin/wine /Users/name/Desktop/Info/wine/SMBX 38A/smbx.exe  0 1 1 %53%4D%42%58%41%72%67%73%7C%32%30%2C%30%2C%30%7C%31%2C%30%2C%31%2C%30%7C%2C%30%2C%30

using this path now:/Applications/Wine Stable.app/Contents/MacOS/wine

**Comment by Wohlstand** [comment]
Did you installed the necessary things? SMBX38A needs:
- vbrun6
- quartz
- directx9

**Comment by M0REKZ** [comment]
im having problems with winetricks, ill search for mirrors for this things

**Comment by Wohlstand** [comment]
I think, you will need to use PlayOnMac as its a simplier way to get a full Wine toolchain with adding of necessary libraries out of box

**Comment by M0REKZ** [comment]
what am I actually doing? SMBX 38A runs fine when I double click on it, (but the editor dont work good)

**Comment by Wohlstand** [comment]
Then, means a Wine setup is incorrect. I side of Wine setup window please use test buttons to verify the wine works.

**Comment by M0REKZ** [comment]
Wait, I'm realizing that the path I select is wrong, rightly that weird "/ bin / wine /"

**Comment by M0REKZ** [comment]
i found the Wine Folder (Before it, i used Wine Bin :T), although I suggest you use the default wine location like "/ Applications / Wine Stable.app/Contents/Resources/wine/"

now i have the error "impossible to prepare a temp file for a test run"

**Comment by Wohlstand** [comment]
> now i have the error "impossible to prepare a temp file for a test run"

That means, it has some problem with a temp folder: it needs a writable temporary folder that will be used to store the data required for a level testing in 38A.

**Comment by Wohlstand** [comment]
Closing because of no responce for a long time.
