### ISSUE TITLE
Autoscroll not work

### ISSUE THREAD

**Issue by LoveBodhi** [WohlSoft/PGE-Project#402]
When I using moondust engine on Autoscroll Events, it simply crash (Level Error). I think this isn't implemented at currently......

**Comment by Wohlstand** [comment]
Can you upload your level that reproduces this bug? (pack it into ZIP and drop it here. If some important servers got banned, use YandexDisk)

**Comment by LoveBodhi** [comment]
EDIT: This works on PGE Engine, therefore I have to close
