### ISSUE TITLE
Unable to build master on Archlinux

### ISSUE THREAD

**Issue by Develon5543** [WohlSoft/PGE-Project#410]
**Which component?**
Mostly vptrlist.h. The version of PGE-Project I tried to compile is commit dc1771df2d1346be57d60437d7ad0acf06bf4e4f

**Describe the bug**
I am unable to compile this program on Archlinux. Errors are related to vptrlist.h, and the error log will be below.

**To Reproduce**
1. `git clone --recursive -j4 https://github.com/WohlSoft/PGE-Project.git`
2. `cd PGE-Project`
3. `git submodule init`
4. `git submodule update`
5. Move SMBX2-Integration to ~/.PGE_Project/configs/
6. `./generate_paths.sh`
7. `./build.sh`

**Expected behavior**
PGE-Project should be compilable.

**Crash report and log files**
[Terminal output](https://pastebin.com/0QYZHUqz)

**Desktop specs (please complete the following information):**
 - OS: Archlinux
 - Version: (Rolling, fully up-to-date at the time of writing)

**Comment by Wohlstand** [comment]
Absence of `ssize_t` (signed `size_t`)? :thinking: Does it at `stddef.h`? Or at `unistd.h`?

P.S. One note I should fix:
```
CMake Deprecation Warning at _common/res_generator/CMakeLists.txt:1 (cmake_minimum_required):
```

**Comment by Wohlstand** [comment]
Just now I sent some patches, please pull and try to build again.

**Comment by Develon5543** [comment]
Hiya. After pulling in the latest patches and recompiling, I get the same issue more or less. [Here](https://pastebin.com/CjXAuNcy) is the logs for that.

**Comment by Wohlstand** [comment]
@Develon5543 , please try again :thinking:

**Comment by Develon5543** [comment]
Yes, that commit successfully compiled. Thank you for your time. :)

**Comment by Wohlstand** [comment]
:fox_face: :+1:
