### ISSUE TITLE
[Editor] Unable to save levels on Archlinux

### ISSUE THREAD

**Issue by Develon5543** [WohlSoft/PGE-Project#411]
**Which component?**
Editor version 0.3.2-beta (rev 2abc63fb5-master, date December 11th, 2020 @ 18:44:46)

**Describe the bug**
I am able to save worlds just fine, but when I try to save a level, an error occurs and my entire editor freezes and has to be killed.

**To Reproduce**
1. Start the editor
2. Click on "new level"
3. Open level properties
4. Uncheck "Appear in Mario Challenge"
5. Set level name
6. Open section settings
7. Set background image
8. Set music (built-in, not custom)
9. Enable Offscreen exit
10. Click Save button
11. Press save again
12. \*Editor freezes\*

**Expected behavior**
A save window should pop up and ask me where to save the level.

**Screenshots**
[Screenshot](https://i.imgur.com/jKgGGme.png) of desktop after this bug occurs

**Crash report and log files**
[PGE_Editor_log_2020-12-11_19-36-44.txt](https://github.com/WohlSoft/PGE-Project/files/5682444/PGE_Editor_log_2020-12-11_19-36-44.txt)
[PGE_Engine_log_2020_12_11_18_53_32.txt](https://github.com/WohlSoft/PGE-Project/files/5682445/PGE_Engine_log_2020_12_11_18_53_32.txt)
(For some reason, I get an engine log as well, so I uploaded that as well)

**Desktop specs (please complete the following information):**
 - OS: Archlinux
 - Version: Rolling

**Comment by Wohlstand** [comment]
The engine log appears in only a condition when you had to run it once upon.
However, seems the freeze is a result of a conflict between libPNG and system libPNG, which came from GTK or something like. :thinking: 

Please rebuild the project with the next CMake args:
```
-DUSE_SYSTEM_LIBC=ON -DUSE_SYSTEM_LIBFREETYPE=ON -DUSE_SYSTEM_LIBPNG=ON -DUSE_SYSTEM_LIBJPEG=ON -DUSE_SYSTEM_SDL2=ON -DUSE_SYSTEM_SQLITE=ON
```
or just by `./build.sh` script next:
```
./build.sh system-libs
```

Was save-dialog Qt-ish or default environment was?

Also, try to build the debug version:
```
./build.sh debug system-libs
```
And try to run it with a debugger, then stop the moment where it got frozen, then use `bt` command to get the stack list.

P.S. You can open the main CMake project in Qt Creator IDE (or any other you have), and try to build it with a debug configuration :thinking:

**Comment by Develon5543** [comment]
Hm this is super odd.
```
== SDL2 will be used from system!
CMake Error at /usr/lib64/cmake/SDL2/SDL2Targets.cmake:4 (message):
  CMake >= 2.6.0 required
Call Stack (most recent call first):
  /usr/lib64/cmake/SDL2/SDL2Config.cmake:1 (include)
  _common/library_SDL2.cmake:54 (find_package)
  CMakeLists.txt:76 (include)
```
```
[develon@FoatOS ztemp]$ cmake --version
cmake version 3.19.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by Wohlstand** [comment]
Seems some conflict with a GTK-bases save dialog, at me that sometimes happens various glitches with GTK dialog:
- when I start from a desktop at XFCE, GTK-save dialog is transparent window border with nothing inside
- when I built thing with non-system libPNG, I get crash on attempt to open save dialog because of conflict: libpng request from the gtk goes into libpng I linked, and crash happens

**Comment by Wohlstand** [comment]
The workaround is forcing the built-in Qt'ish dialog and avoid calling it from GTK

**Comment by Wohlstand** [comment]
One question: did you used Qt from the package manager or externally-downloaded?

**Comment by Develon5543** [comment]
Sorry for the late reply. I use the latest version available from my package manager.

**Comment by Wohlstand** [comment]
Just now I made this thing: https://github.com/WohlSoft/PGE-Project/commit/41531b0e3e6c850999be9bf6f8f2d25afbe24948
I hope it solves the freeze you have. If you'll don't use png/jpeg libraries from the system, the native dialog option will be disabled, file dialogs will just use Qt built-in one, mainly used as a fallback.

**Comment by Develon5543** [comment]
Thank you. That fixed the issue on my end.
