### ISSUE TITLE
Cannot Execute binary file: Exec format error - Ubuntu 20.10 Raspberry Pi 4B (ARM64)

### ISSUE THREAD

**Issue by ghost** [WohlSoft/PGE-Project#425]
**Cannot Execute binary file: Exec format error**
When I follow the build instructions from [Link](https://wohlsoft.ru/pgewiki/Building_PGE_From_sources#Building_for_Linux), After I have "chmodded" after downloading the file, the "cmodding" has no errors but when I try to run the file I get: `bash: ./qt-unified-linux-x64-online-run: cannot execute binary file: Exec format error` I've seen this before when I try to run software for 64 bits on 32 bits or when I try to run x86 software on Arm.

Any help would be appreciated, PGE looks like the perfect engine for making platformer games :D

**Comment by Wohlstand** [comment]
You should install the Qt from the system, you don't need to install the Qt by the installer, especially on ARM :joy_cat: 

Simply install the Qt by the next run:
```
sudo apt-get install qt5-default qt5-qmake qttools5-dev qttools5-dev-tools libqt5gui5 \
libqt5core5a libqt5widgets5 libqt5concurrent5 libqt5qml5 qtdeclarative5-dev libqt5network5 \
qt5-image-formats-plugins qt5-gtk-platformtheme qt5dxcb-plugin qtwayland5 libqt5waylandclient5
```
Also, if you want to get the IDE, also install  the `qtcreator`. :fox_face:

**Comment by CMDR-Piboy314** [comment]
After installing all those packages & the qtcreator I still get the exact same error :(

**Comment by Wohlstand** [comment]
You don't need to run the `qt-unified...` at all, this is completely useless step at you

**Comment by Wohlstand** [comment]
As you had to install all listed dependencies, go start to do the build itseld

**Comment by CMDR-Piboy314** [comment]
Sorry, my account was deleted because I am underage to use this site.

**Comment by Wohlstand** [comment]
Cya, @ghost!
I hope, you did your build successfully. :fox_face:
