### ISSUE TITLE
[Editor] Import custom data not working

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#71]
1. Tools->Custom data->Import
2. Select directory which contains custom stuff, like graphics and NPC settings.
3. Nothing happens, including nothing new appearing in level directory.
   This command should copy contents from the given folder into level directory and then update main editor window to reflect changes.

**Comment by KevinW1998** [comment]
Could you try to drag and drop the folder containing the custom content
into the pge level window?
Am 28.09.2015 16:52 schrieb "Alucard648" <notifications@github.com>:

**Comment by Alucard648** [comment]
What a great discovery! Drag & drop works like magic. Where did you read about it?

**Comment by KevinW1998** [comment]
I didn't read about it, I implemented that feature. Later Wohlstand wanted to add that via menu item, but it probably somehow broke.

**Comment by Alucard648** [comment]
On related note: Importing custom data via drag and drop does not overwrite files existing in level folder.

**Comment by Wohlstand** [comment]
Okay, after long time of waiting, let's fix this feature as it must make easier life for newbies!

**Comment by Wohlstand** [comment]
I had to fix this, should work now... Please test.

**Comment by Alucard648** [comment]
Works as intended and suggsted.

**Comment by Wohlstand** [comment]
Perfect!
