### ISSUE TITLE
"Edit tileset" button opens first tileset in list, instead of current one.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#81]
1. Open level that has multiple custom tilesets, level-specific or not.
2. Go to the non-first one and click it`s "edit tileset" button with pencil icon.
3. First tileset in list will be opened in editor, instead of the chosen one. Had to manually open needed tileset via "Open" button in tileset editor.

**Comment by Wohlstand** [comment]
Hm, wired, I just tested - everything is works. I think, I will upload update in nearest time and then try out it (I think, was a dumb bug which already fixed)

**Comment by Wohlstand** [comment]
New version has been uploaded, you can try out it and check, are you still have trouble with this thing?

**Comment by Alucard648** [comment]
Issue is gone, Thank you.

**Comment by Alucard648** [comment]
Had to reopen issue beause the bug has reappeared again. Reproduction steps are the same.

**Comment by Wohlstand** [comment]
This bug has been fixed now. So, no more using tileset title to search (target tileset to edit), using filename only.

**Comment by Alucard648** [comment]
Bug fix confirmed.
