### ISSUE TITLE
[Engine] Suggestion for slope behavior/collisions

### ISSUE THREAD

**Issue by jpmac26** [WohlSoft/PGE-Project#84]
I would program this myself if I knew how, but I have a very hard time understanding how positions and "nearest blocks" are calculated.

Anyway, in the real SMBX, slopes cause Mario to decelerate horizontally a little bit when walking uphill, which does not currently happen in PGE (although it's probably not ready to be programmed yet XD).

Also, to help make sure the player and NPCs are colliding properly with slopes when walking, I think we should test several nearby blocks within about 1 or 2 block's reach of the player/NPC in both the X and Y directions, and see if it is a slope tile. We should test blocks in order of "close-ness" so that the closest block will be tested first, then the second closest, etc.

If any of these blocks are slope blocks, we should give the player's collision testing a greater "margin of error/travel" before it reports that the player is not colliding with the floor, so that when a player walks down a slope, they aren't glitching between "falling" and "standing" constantly.

Also, we may want to modify the player's movement (or position) manually to follow the slope of the hill, BUT ONLY IF the player's horizontal speed is less than (gravity \* slope of hill as double \* 2) or something like that, so the player is not dragged down a slope even when they are going so fast that they should be flying off it. Sorry for the long text, and I apologize if I was confusing, please let me know if I need to clarify anything about my idea.

**Comment by Wohlstand** [comment]
"Nearest block" function located in base object's place, collision check per side functions are inline and I made separated header for them. There are two "Nearest block" functions: one of them detects that block which has nearest center to center of playable character by horizontal and by vertical axis.
Any collision parts of player: detection of colliding elements and resolving of collisions are in the Engine/scenes/level/player folder which a "lvl_player_collisions.cpp" (for NPCs is a lvl_npc_collisions.cpp).
Anyway I wasn't finished works over them. Anyway, "don't hurt character while it flying up" is true workarround which is not good thing, + to resolve some troubles I should move some contact reactions (hurt, stomp, kill) into post-collide place

**Comment by Wohlstand** [comment]
Now I'm working on new physical engine which now has perfect physics:
https://github.com/Wohlhabend-Networks/MiniPhysics-By-38A
I still fix something until I will apply to PGE Engine side

**Comment by Wohlstand** [comment]
I think, this is no more actual since new physical engine with better slopes processing has been done
